# Generated by Django 6.0.1 on 2026-02-10 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ('id',), 'verbose_name': 'продукт', 'verbose_name_plural': 'Продукты'},
        ),
    ]
